"""add expires_at index

Revision ID: 36216db1688e
Revises: b63c9540d621
Create Date: 2026-08-10 19:31:06.762912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36216db1688e'
down_revision: Union[str, Sequence[str], None] = 'b63c9540d621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_links_expires_at'), 'links', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_expires_at'), table_name='links')
    # ### end Alembic commands ###
