"""add composite unique constraint for url_hash and user_id

Revision ID: b63c9540d621
Revises: 52ce834b5b60
Create Date: 2026-08-06 18:02:21.728272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b63c9540d621'
down_revision: Union[str, Sequence[str], None] = '52ce834b5b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_url_hash'), table_name='links')
    op.create_index(op.f('ix_links_url_hash'), 'links', ['url_hash'], unique=False)
    op.create_unique_constraint('uq_url_hash_user_id', 'links', ['url_hash', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_url_hash_user_id', 'links', type_='unique')
    op.drop_index(op.f('ix_links_url_hash'), table_name='links')
    op.create_index(op.f('ix_links_url_hash'), 'links', ['url_hash'], unique=True)
    # ### end Alembic commands ###
